name: jsdelivr Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H)" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ./output/user_result.m3u
            ./output/user_result.txt

      - name: Purge jsdelivr CDN
        run: |
          cd output || exit 1
          for file in $(ls); do
            if [[ "$file" == user_result* ]]; then
              curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
            fi
          done
      
